[server]
host = "[::]" # 服务监听地址, 默认为 127.0.0.1
port = 8080 # 服务监听端口, 默认为 8080
mode = "debug" # 运行模式：debug 或 release 或 test, 默认为 debug
ticker = 5 # 自定义的服务心跳间隔时间, 单位：秒, 默认为 5

[logger]
level = -1  # 日志级别：-1 - Debug, 0 - Info, 1 - Warn, 2 - Error, 3 - DPanic, 4 - Panic, 5 - Fatal, 默认为 0
format = "json" # json 或 console, 默认为 console
output_path = "./logs/app.log" # 日志输出路径, 默认为 ./logs/app.log

[etcd]
endpoints = ["etcd:2379"] # etcd 服务地址, 默认为 ["localhost:2379"]
timeout = 5 # etcd 连接超时时间, 单位：秒, 默认为 5

[service] # 用于服务注册时的配置
id = "service-1" # 服务 ID, 默认为 service-1
name = "service" # 服务名称, 默认为 service
host = "monitor" # 服务地址, 默认为 localhost
port = 8080 # 服务端口, 默认为 8080
lease_time = 5 # etcd 服务注册租约时间, 单位：秒, 默认为 5
interval = "5s"  # consul 健康检查间隔
timeout = "3s"   # consul 超时时间
deregister_after = "1m"  # consul 多久之后注销服务

[consul]
address = "consul:8500" # consul 服务地址, 默认为 consul:8500
timeout = 5 # consul 连接超时时间, 单位：秒, 默认为 5