[server]
host = "[::]" # 服务监听地址, 默认为 127.0.0.1
port = 8080 # 服务监听端口, 默认为 8080
mode = "debug" # 运行模式：debug 或 release 或 test, 默认为 debug
ticker = 5 # 自定义的服务心跳间隔时间, 单位：秒, 默认为 5

[logger]
level = -1  # 日志级别：-1 - Debug, 0 - Info, 1 - Warn, 2 - Error, 3 - DPanic, 4 - Panic, 5 - Fatal, 默认为 0
format = "json" # json 或 console, 默认为 console
output_path = "./logs/app.log" # 日志输出路径, 默认为 ./logs/app.log

[etcd]
endpoints = ["localhost:2379"] # etcd 服务地址, 默认为 ["localhost:2379"]
timeout = 5 # etcd 连接超时时间, 单位：秒, 默认为 5

