services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_sd:/etc/prometheus/file_sd_configs
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ETCD_NAME=etcd-1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd-1=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - monitoring
    restart: unless-stopped

  consul:
    image: bitnami/consul:latest
    container_name: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=0.0.0.0
      - CONSUL_DATACENTER=dc1
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - monitoring
    restart: unless-stopped

  monitor:
    image: monitor-service:latest
    container_name: monitor
    ports:
      - "8080:8080" 
    volumes:
      - prometheus_sd:/etc/prometheus/file_sd_configs 
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_sd: