global:
  scrape_interval: 15s # 全局抓取间隔

scrape_configs:
  # Prometheus 自身的监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # 监控 ETCD 的状态
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']

  # 动态配置的服务发现
  - job_name: 'dynamic_services'
    file_sd_configs:
      - files:
          - '/etc/prometheus/file_sd_configs/targets.json'
        refresh_interval: 5s